version: '3.8'

networks:
    my_network:
        driver: bridge

services:
    onlinestore:
        image: ${DOCKER_REGISTRY-}onlinestore
        build:
            context: .
            dockerfile: OnlineShop/Dockerfile
        networks:   
            - my_network
        ports:
            - "8080:80" 
            - "8081:443"
        environment:
              - ASPNETCORE_URLS=https://+;http://+
              - ASPNETCORE_Kestrel__Certificates__Default__Password=Asdfg12345
              - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/OnlinStoreCert.pfx
              - ASPNETCORE_HTTPS_PORTS=8081
        volumes:
            - ./UserSecrets:/root/.microsoft/usersecrets
            - ./.aspnet/https/OnlinStoreCert.pfx:/https/OnlinStoreCert.pfx
 
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sql_server
        environment:
            MSSQL_SA_PASSWORD: "Asdfg12345"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        networks:
            - my_network
        volumes:
            - sqlserverdata:/var/opt/mssql

volumes:
    sqlserverdata:
        driver: local
